name: Testing uploader

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Upload README
      uses: repaction/uploader@master
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      with:
        src_file: README.md
        dst_file: /devel/README.md

